### ISSUE TITLE
App is crashing in Android 13 , getting issue Injecting input events ,in line no. MultiSpinnerSearch.java:185

### ISSUE THREAD

**Issue by DevTheKing** [pratikbutani/MultiSelectSpinner#109]
Fatal Exception: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3040)
       at android.os.Parcel.createException(Parcel.java:3024)
       at android.os.Parcel.readException(Parcel.java:3007)
       at android.os.Parcel.readException(Parcel.java:2949)
       at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
       at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1151)
       at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1180)
       at android.app.Instrumentation.sendKeySync(Instrumentation.java:1135)
       at android.app.Instrumentation.sendKeyDownUpSync(Instrumentation.java:1147)
       at com.androidbuts.multispinnerfilter.MultiSpinnerSearch.lambda$onCancel$0(MultiSpinnerSearch.java:185)
       at com.androidbuts.multispinnerfilter.-$$Lambda$MultiSpinnerSearch$p9xhRiNPdc-qw9SrA8LUwZsjeq0.run()
       at java.lang.Thread.run(Thread.java:1012)

**Comment by MahmoudMagdyEllawatty** [comment]
same issue here.
do you find any solution?

**Comment by DevTheKing** [comment]
@MahmoudMagdyEllawatty  I downloaded the library and added it manually in my projects and given following permission in my Manifest.xml file
`<uses-permission android:name="android.permission.INJECT_EVENTS"/>`

**Comment by Rahul-Routh** [comment]
<uses-permission android:name="android.permission.INJECT_EVENTS"/> is not inserted in 
Permission is only granted to system apps

**Comment by Bahul045** [comment]
I have facing same issue, it crash in android 13

**Comment by anshucpr** [comment]
> @MahmoudMagdyEllawatty I downloaded the library and added it manually in my projects and given following permission in my AndroidManifest.xml file `<uses-permission android:name="android.permission.INJECT_EVENTS"/>` It fixed the problem

not fix issue

**Comment by monossido** [comment]
Not fixed!!

**Comment by rlebranchu** [comment]
_Hi !
Has anyone found a solution for non-system_app applications?_

**Edited :** 
I've found a solution to prevent dropdowns from appearing without using Instrumentation.

Just replace : 
>/**
>        * To hide dropdown which is already opened at the time of performClick...
>         * This code will hide automatically and no need to tap by user.
>         */
>        new Thread(new Runnable() {
>            @Override
>            public void run() {
>                Instrumentation inst = new Instrumentation();
>                inst.sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);
>            }
>        }).start();

By
>this.onDetachedFromWindow();

This code will hide dropdown options when dialog will be cancelled.
Hope this helps.
