### ISSUE TITLE
Getting Fatal Exception: java.lang.SecurityException for some users

### ISSUE THREAD

**Issue by kusal** [pratikbutani/MultiSelectSpinner#93]
I have been getting following error from few installs.

`Fatal Exception: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
       at android.os.Parcel.createException(Parcel.java:2071)
       at android.os.Parcel.readException(Parcel.java:2039)
       at android.os.Parcel.readException(Parcel.java:1987)
       at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:878)
       at android.hardware.input.InputManager.injectInputEvent(InputManager.java:886)
       at android.app.Instrumentation.sendKeySync(Instrumentation.java:1082)
       at android.app.Instrumentation.sendKeyDownUpSync(Instrumentation.java:1092)
       at com.androidbuts.multispinnerfilter.MultiSpinnerSearch.lambda$onCancel$0(MultiSpinnerSearch.java:185)
       at com.androidbuts.multispinnerfilter.-$$Lambda$MultiSpinnerSearch$p9xhRiNPdc-qw9SrA8LUwZsjeq0.run()
       at java.lang.Thread.run(Thread.java:929)`

`Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventInternal(InputManagerService.java:808)
	at com.android.server.input.InputManagerService.injectInputEventInternal(InputManagerService.java:773)
	at com.android.server.input.InputManagerService.injectInputEvent(InputManagerService.java:768)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:403)
	at android.os.Binder.execTransactInternal(Binder.java:1028)`

**Comment by Franchy1337** [comment]
This is due to new permissions on Android 13. - This means only Android 13 devices are affected. These can only be set for system apps. 
My workaround was to remove the MultSelectSpinner lib from my App ( remove implementation in the gradle file) and add all files directly to my app. 
Hope that helps.

**Comment by ateeqrehman33** [comment]
Hi @Franchy1337 How did you add all files to app directly without implementation in gradle file..??

**Comment by manishmghr** [comment]
Simply Clone this Project and Use All Code XMl and Resource File Into Your Project and
 Delete Dependency and XML of This library.
